name: deploy-command
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
      - name: Build Image
        run: |
          echo "Building Starpunk Image version `cat VERSION`"
          ./renderhtml.sh
          docker build -t ghcr.io/eilidhmae/starpunk:latest .
          docker tag ghcr.io/eilidhmae/starpunk:latest ghcr.io/eilidhmae/starpunk:`cat VERSION`
          git tag "v`cat VERSION`" HEAD
          git push --tags
      - name: Push Image
        run: |
          docker push ghcr.io/eilidhmae/starpunk:latest
          docker push ghcr.io/eilidhmae/starpunk:`cat VERSION`
      - name: Add Reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
